---
- hosts: all
  become: yes
  gather_facts: yes
  tasks:
  - name: install webserver on ubuntu
    apt:
      name: apache2
      state: present
      
  - name: start webserver
    service:
     name: apache2
     state: started